name: Deploy Frontend

on:
  push:
    branches:
      - dev  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Docker image with commit hash tag
        run: |
          docker build \
            --build-arg VITE_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }} \
            -t menonijesus/frontend-dev:${{ env.TAG }} \
            -t menonijesus/frontend-dev:latest .

      - name: Push both tags
        run: |
          docker push menonijesus/frontend-dev:${{ env.TAG }}
          docker push menonijesus/frontend-dev:latest